project_id = "dpmyursjpbscrfbljtha"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_user_attributes = false

[functions.admin-security-api]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-send-magic-link]
verify_jwt = false

[functions.google-reviews-sync]
verify_jwt = false

[functions.integrations-upsert]
verify_jwt = false

[functions.integrations-list]
verify_jwt = false

[functions.integrations-delete]
verify_jwt = false

[functions.secure-data-deletion-request]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.test-email-connection]
verify_jwt = false

[functions.test-payment-method]
verify_jwt = false

[functions.push-send]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.generate-dkim-keys]
verify_jwt = false

[functions.mailchannels-dkim-gen]
verify_jwt = false

[functions.mailchannels-test]
verify_jwt = false

[functions.stripe-create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-get-customer]
verify_jwt = false
